force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description
  >Stores quote details such as start and end date total amount etc</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/applications/force-app/main/default/objects/Quote__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QuoteDto.cls
public with sharing class QuoteDto extends BaseDto {
  @AuraEnabled
  public Date endDate;
  @AuraEnabled
  public Date startDate;
  public QuoteDto() {
  }
  public QuoteDto(Quote__c quote) {
    super(quote);
    this.endDate = quote.EndDate__c;
    this.startDate = quote.StartDate__c;
  }

  public override SObject refreshSo() {
    return null;
  }
  @AuraEnabled
  public static QuoteDto getOrUpdateQuote(Id recordId, date startDate, date endDate){
      quote__c testQuote = [Select EndDate__c, StartDate__c from Quote__c where id=:recordId];
      QuoteDto WrapperCls= new QuoteDto(); 
      if(startDate == null && endDate==null){
        WrapperCls = new QuoteDto(testQuote);
        system.debug(WrapperCls);
      }
      else{
        testQuote.EndDate__c = endDate;
        testQuote.StartDate__c = startDate; 
        WrapperCls = new QuoteDto(testQuote);
        update testQuote;
      }
      return WrapperCls;

  }
 

}